---

- name: Create Python virtual environment directory
  file:
    path: "{{ waiwera_path }}/venv"
    state: directory

- name: Create Python virtual environment
  command: "python3 -m venv {{ waiwera_path }}/venv"

- name: Activate Python virtual environment
  shell: "source {{ waiwera_path }}/venv/bin/activate"
  args:
    executable: /bin/bash

- name: Update pip to latest version with pip
  pip:
    name: pip
    executable: "{{ waiwera_path }}/venv/bin/{{ pip_ex }}"
    extra_args: --upgrade
  tags:
    - pip
  register: pip_error
  ignore_errors: True

- name: Install meson via pip
  pip:
    name: "{{ meson_version }}"
    executable: "{{ waiwera_path }}/venv/bin/{{ pip_ex }}"

- name: Test for pre-existing ninja install
  command: ninja --version
  register: ninja_test
  ignore_errors: True

- name: Install from ninja source
  import_role:
    name: ninja
  tags:
    - ninja
  when: (ninja_test is failed) or (ninja_build == 'true')

- name: Install zofu from source
  import_role:
    name: zofu
  tags:
    - zofu
  when: zofu_build == 'true'

- name: Install fson from source
  import_role:
    name: fson
  tags:
    - fson
  when: fson_build == 'true'

- name: Check if waiwera directory exists already
  stat:
    path: "{{ waiwera_path }}/LICENSE"
  register: waiwera_dir

- name: Fetch waiwera from repository if version is not local
  git:
    repo: "https://{{ waiwera_repo }}"
    dest:  "{{ waiwera_path }}"
    version: "{{ waiwera_version }}"
    update: yes
    force: yes
  register: waiwera_git
  tags:
    - fetch
  when: waiwera_version != 'local'

- name: Install PETSc
  import_role:
    name: petsc
  tags:
    - petsc

- name: Setup and build Waiwera
  import_role:
    name: waiwera
  tags:
    - waiwera
