---

- name: Test for pre-existing mpi install
  command: mpiexec --version
  register: mpi_test
  ignore_errors: True

- name: mpi - add mpi to petsc install
  block:

  - set_fact:
      petsc_mpi:
        - download-mpich

  - set_fact:
      petsc_options: "{{petsc_options + petsc_mpi}}"

  when: mpi_test is failed
  tags:
    - never
    - local

- name: Run the common tasks to setup waiwera on a system with no root access
  import_tasks: setup.yml

- name:  Build waiwera and depencies
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ bin_path }}:{{ local_bin }}:{{ petsc_bin }}"
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
    LC_TYPE: en_US.UTF-8
    PETSC_DIR: "{{ petsc_path }}"
    PETSC_ARCH: "{{ petsc_arch }}"
    PKG_CONFIG_PATH: "{{ lookup('env','PKG_CONFIG_PATH') }}:{{ pkgconfig_path }}"
  import_tasks: build.yml
