# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 2.2.4"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/fedora-29"
  config.vm.synced_folder ".", "/vagrant/"
  config.vm.define :waiwera, primary: true do |waiwera|
    waiwera.vm.provision :file, source: "../../ansible", destination: "/tmp/ansible"
    waiwera.vm.provision :shell, inline: "cp -r /tmp/ansible /"
    waiwera.vm.provision :shell, inline: "dnf install python-pip -y && pip install -U ansible"
    waiwera.vm.provision "ansible_local" do |ansible|
      # ansible.limit = 'waiwera'
      ansible.verbose = "vv"
      ansible.playbook = "/ansible/site.yml"
      ansible.raw_arguments = [
        '-e "app_user=vagrant"',
        '-e "app_group=vagrant"',
        '--skip-tags=docker,clean',
      ]
    end
    waiwera.vm.provision :shell, inline: "sh /etc/profile.d/opt_paths.sh; cd /opt/app/waiwera; python unit_tests.py", privileged: false
    waiwera.vm.hostname = "waiwera-fedora"
  end
  config.vm.provider :virtualbox do |v|
#    v.gui = true
    v.memory = 4096
  end
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
end
