---

- name: Build
  block:

  - name: Clean build path
    file:
      state: absent
      path: "{{ waiwera_path }}/build/"

  - name: waiwera - Meson build
    shell: meson setup build --buildtype={{ petsc_arch }} --prefix={{ base_dir }} -Dlibdir=lib -Dset_rpath=true
    args:
      chdir: "{{ waiwera_path }}"
      executable: /bin/bash
    tags:
      - meson
      - build

  - name: waiwera - meson compile
    shell: meson compile -C build
    args:
      chdir: "{{ waiwera_path }}"
    tags:
      - ninja
      - build

  when: (waiwera_build == 'true')
