program tests

  ! Driver program for FRUIT unit tests in:
  ! test/src/timestepping_test.F90

  ! Generated by FRUITPy.

  use fruit
  use fruit_mpi
  use timestepping_test
  use setup_module

  implicit none
  integer :: size, rank, ierr

  call init_fruit
  call setup

  call MPI_COMM_SIZE(PETSC_COMM_WORLD, size, ierr)
  call MPI_COMM_RANK(PETSC_COMM_WORLD, rank, ierr)

  ! test/src/timestepping_test.F90:
  call run_test_case(test_linear, "Linear function")
  call run_test_case(test_exponential, "Exponential function")
  call run_test_case(test_logistic, "Logistic equation")
  call run_test_case(test_nontrivial_lhs, "Nontrivial LHS")
  call run_test_case(test_nonlinear_lhs, "Nonlinear LHS")
  call run_test_case(test_heat1d, "1-D heat equation PDE")

  call fruit_summary_mpi(size, rank)
  call fruit_finalize_mpi(size, rank)
  call teardown

end program tests