# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 2.2.4"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.synced_folder ".", "/vagrant/"
  config.vm.define :waiwera, primary: true do |waiwera|
    waiwera.vm.provision "ansible_local" do |ansible|
      # ansible.limit = 'waiwera'
      ansible.provisioning_path = "/vagrant/install/ansible"
      ansible.verbose = "vv"
      ansible.playbook = "vagrant.yml"
    end
    waiwera.vm.provision :shell, inline: "cd /vagrant; python unit_tests.py", privileged: false
    waiwera.vm.hostname = "waiwera-arch"
  end
  config.vm.provider :virtualbox do |v|
#    v.gui = true
    v.memory = 4096
  end
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
end
