---

build_tools:
  - git
  - pkg-config
  - valgrind
  - make
  - cmake
  - automake

ninja:
  - ninja-build

python_dependencies:
  - python3
  - python3-dev
  - python3-setuptools

compilers:
  - gcc
  - g++
  - gfortran

libraries:
  - libblas-dev
  - liblapack-dev

mpi:
  - mpich
  - libmpich-dev
  - openssh-client

petsc_dependencies:
  - bison
  - flex
  - zlib1g-dev
  - libtool

pip_install:
  - python3-pip

pip_ex: pip3

meson_version: meson

petsc_options:
  - download-fblaslapack
  - download-triangle
  - download-netcdf
  - download-exodusii
  - download-pnetcdf
  - download-ptscotch
  - download-chaco
  - download-zlib
  - download-hdf5
  - with-debugging=0

petsc_options_compiler_release_native:
  - "COPTFLAGS='-O3 -march=native -mtune=native'"
  - "CXXOPTFLAGS='-O3 -march=native -mtune=native'"
  - "FOPTFLAGS='-O3 -march=native -mtune=native'"

petsc_options_compiler_release_generic:
  - "COPTFLAGS='-O3 -march=x86-64 -mtune=generic'"
  - "CXXOPTFLAGS='-O3 -march=x86-64 -mtune=generic'"
  - "FOPTFLAGS='-O3 -march=x86-64 -mtune=generic'"
